name: lama
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - cudatoolkit>=11.8  # optional: ensures GPU compatibility on local installs
  - pip:
      - -r requirements.txt
