name: lama-gpu
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - numpy=1.24.3
  - scipy=1.11.4
  - matplotlib=3.7.2
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - scikit-image=0.21.0
  - opencv=4.8.1
  - pillow=10.0.1
  - tqdm=4.66.1
  - pyyaml=6.0.1
  - packaging=23.2
  - joblib=1.3.2
  - tabulate=0.9.0
  - requests=2.31.0
  - ffmpeg=6.0
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - cudnn=8.7
  - pip:
    - albumentations==1.3.1
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - pytorch-lightning==2.1.2
    - kornia==0.7.0
    - webdataset==0.2.86
    - easydict==1.10
    - tensorboard==2.15.1
    - imgaug==0.4.0
    - shapely==2.0.2
    - braceexpand==0.1.7
    - wldhx-yadisk-direct==0.0.6
    - setuptools==68.2.2
    - wheel==0.42.0