# LaMa with Fast Fourier Convolution
_target_: src.lightning_module.InpaintingLightningModule

generator_config:
  type: ffc
  input_nc: 4  # RGB + mask
  output_nc: 3  # RGB
  ngf: 64
  n_downsampling: 3
  n_blocks: 9
  norm_layer: BatchNorm2d
  padding_type: reflect
  activation_layer: ReLU
  up_norm_layer: BatchNorm2d
  up_activation: ReLU
  
  # FFC specific parameters
  init_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
  downsample_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0.75
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  upsample_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0
  output_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0

discriminator_config:
  type: multiscale
  input_nc: 3
  ndf: 64
  n_layers: 3
  norm_layer: BatchNorm2d
  use_sigmoid: false
  num_D: 3
  getIntermFeat: true

loss_config:
  l1_weight: 1.0
  perceptual_weight: 1.0
  adversarial_weight: 0.1
  feature_matching_weight: 10.0
  resnet_pl_weight: 30.0
  hf_weight: 1.0
  use_lpips: true
  use_resnet_pl: true
  resnet_pl_path: null
  adversarial_loss_type: lsgan
  use_r1_penalty: false
  r1_gamma: 10.0
  discriminator_update_ratio: 1

optimizer_config:
  optimizer_type: adam
  generator_lr: 1e-4
  discriminator_lr: 1e-4
  betas: [0.5, 0.999]
  weight_decay: 1e-4

scheduler_config:
  type: cosine
  T_max: 100
  eta_min: 1e-6

automatic_optimization: false