# WandB logger configuration
type: wandb
project: lama-inpainting
entity: null  # Set your wandb entity/username here
tags: 
  - lama
  - inpainting
  - fourier-convolution
notes: "LaMa inpainting model training with FFC"
mode: online  # online, offline, or disabled
save_code: true