name: CI

on:
  push:
    branches: [ main, master, refactor-oss-layout ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
          pip install pytest omegaconf hydra-core pytorch-lightning
      - name: Run tests
        run: pytest -q